use_langchain: False
langchain_rewriter_type : 'gpt-4o-mini'
langchain_reader_type : 'gpt-4o-mini'
model_kwargs:
  temperature: 1
  top_p: 1
  presence_penalty : 0
  frequency_penalty: 0
# pretrained_rewriter_model: "Qwen/Qwen2-7B-Instruct"
pretrained_rewriter_model: "/home/wangqi/Projects/LLaMA-Factory/saves/Qwen2-7B-Chat/lora/train_2024-12-08-15-00-00"