use_langchain: False
langchain_rewriter_type : 'gpt-4o-mini'
langchain_reader_type : 'gpt-4o-mini'
model_kwargs:
  temperature: 0
  top_p: 1
  presence_penalty : 0
  frequency_penalty: 0
pretrained_rewriter_model: "/home/wangqi/Projects/LLaMA-Factory/saves/Qwen2.5-7B-Instruct-AWQ/lora/Syllabus_SFT_Qwen_train"
